@indentityUrl_ = http://localhost:5010
@verificationUrl_ = http://localhost:5050

@indentityUrl = http://130.61.177.16:5001/identity
@verificationUrl = http://130.61.177.16:5001/verification
@email = cybul27@gmail.com
@password = test123
@verificationHash = qjtjHyAPHgXJuwiLk9L3bArjEFrHcY5wWs7V3L65LqaSihqJAuXucGhhszWPLmc
###
GET {{indentityUrl}}

###
# @name sign-up
POST {{indentityUrl}}/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}
###
# @name verify
PUT {{verificationUrl}}/verify
Content-Type: application/json

{
    "verificationHash": "{{verificationHash}}"
}

###
# @name resend
PUT {{verificationUrl}}/resend?email={{email}}

###
# @name login
POST {{indentityUrl}}/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name log-out
DELETE  {{indentityUrl}}/sign-out

