@indentityUrl = http://localhost:5010
@verificationUrl = http://localhost:5050
@customerId = 00000000-0000-0000-0000-000000000001
@email = cybul26@gmail.com
@password = test123
###
GET {{indentityUrl}}

###
# @name sign-up
POST {{indentityUrl}}/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}
###
# @name verify
PUT {{verificationUrl}}/verify
Content-Type: application/json

{
    "verificationHash": "hjr8DOcTOByrx772U1L3Q4ZrMJ8ePxT8LbgjSN148sNDniqGW64oxB71ZyqE2G97Y"
}

###
# @name login
POST {{indentityUrl}}/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# @name log-out
DELETE  {{indentityUrl}}/sign-out

