// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VirtualFreezer.AccountVerification.Infrastructure.EF;

#nullable disable

namespace VirtualFreezer.AccountVerification.Infrastructure.EF.Migrations
{
    [DbContext(typeof(VerificationDbContext))]
    [Migration("20221122213931_resends_added_to_verification")]
    partial class resends_added_to_verification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VirtualFreezer.AccountVerification.Domain.Entities.Verification", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VerificationHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Email");

                    b.HasIndex("Email");

                    b.HasIndex("VerificationHash");

                    b.ToTable("Verifications");
                });

            modelBuilder.Entity("VirtualFreezer.AccountVerification.Domain.Entities.Verification", b =>
                {
                    b.OwnsMany("VirtualFreezer.AccountVerification.Domain.Entities.Resend", "_resends", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DateTimeUtc")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("Email");

                            b1.ToTable("Resends", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("Email");
                        });

                    b.Navigation("_resends");
                });
#pragma warning restore 612, 618
        }
    }
}
