name: Account Verififaction build

on:
  push:
    branches: ['master', 'develop']
    paths:
      - 'Gateway/**'
      - .github/workflows/gateway.yml
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the docker image
        run: docker build .  --file Gateway/Dockerfile --tag $DOCKER_USER/virtual-freezer-gateway:latest

      - name: Docker push
        run: docker push  $DOCKER_USER/virtual-freezer-gateway:latest
