name: Account Verififaction build

on:
  push:
    branches: ['master', 'develop']
    paths:
      - 'Gateway/**'
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker login

        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build the docker image
        run: docker buildx build . --file Gateway/Dockerfile --tag $DOCKER_USER/virtual-freezer-gateway:${{ steps.date.outputs.date }}

      - name: Docker push
        run: docker push --platform=linux/arm64 $DOCKER_USER/virtual-freezer-gateway:${{ steps.date.outputs.date }}
